apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mysql-deployment
  labels:
    app: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      nodeName: ip-172-31-39-58
      dnsConfig:
        nameservers:
          - "8.8.8.8"
          - "8.8.4.4"
      containers:
      - name: mysql
        image: datascientest/mysql-k8s:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: "Main"
        volumeMounts:
        - name: mysql-init-scripts
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        startupProbe:
          tcpSocket:
            port: mysql
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: mysql
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: mysql
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      - name: fastapi
        image: localhost:5000/fastapi-user-api:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - |
          sleep 30 &&  # Wait for MySQL to be ready
          python3 -m uvicorn main:server --host 0.0.0.0
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MYSQL_URL
          value: "127.0.0.1"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: "Main"
        - name: MYSQL_PORT
          value: "3306"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        startupProbe:
          httpGet:
            path: /status
            port: http
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 45
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: mysql-init-scripts
        configMap:
          name: mysql-init-scripts